SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER HELLO6 
BEFORE UPDATE 
OF TAKA
ON MONEY
FOR EACH ROW
DECLARE
	A money.id%TYPE;
	B money.name%TYPE;
	C money.taka%TYPE;
BEGIN
	A := :OLD.ID;
	B := :OLD.NAME;
	C := :OLD.TAKA;
	INSERT INTO MONEY1 VALUES(A, B, C);
END;
/