-- HERE EXCEPTION WILL BE CAUGHT WHEN ID<=0 AND WHEN ALL THE INFORMATION IS NOT MATCHED BUT ID IS FOUND IN THE DATABASE.
-- PROCEDURE AND FUNCTION IS ADDED TO THE PACKAGE AND TRIGGER WILL BE CALLED AFTER INSERTION.

SET SERVEROUTPUT ON;
SET VERIFY OFF;

CREATE OR REPLACE PACKAGE MYPACK AS
	FUNCTION SEARCH_ACCOUNT(SID IN SUPPLIER.SID%TYPE,SNAME IN SUPPLIER.SNAME%TYPE,ADDRESS IN SUPPLIER.ADDRESS%TYPE)
	RETURN NUMBER;
	
	PROCEDURE INSERT_DISPLAY(SID IN SUPPLIER.SID%TYPE,SNAME IN SUPPLIER.SNAME%TYPE,ADDRESS IN SUPPLIER.ADDRESS%TYPE,IS_FOUND IN NUMBER);
END MYPACK;
/

CREATE OR REPLACE PACKAGE BODY MYPACK AS
	FUNCTION SEARCH_ACCOUNT(SID IN SUPPLIER.SID%TYPE,SNAME IN SUPPLIER.SNAME%TYPE,ADDRESS IN SUPPLIER.ADDRESS%TYPE)
	RETURN NUMBER IS
	IS_FOUND NUMBER:=0;
	BEGIN
		FOR ACCOUNT IN (SELECT * FROM SUPPLIER) LOOP
			IF ACCOUNT.SID = SID THEN
				IF ACCOUNT.SNAME=SNAME AND ACCOUNT.ADDRESS=ADDRESS THEN
					IS_FOUND:=1;
				ELSE
					IS_FOUND:=-1;
				END IF;
				EXIT;
			END IF;
		END LOOP;
		RETURN IS_FOUND;
	END SEARCH_ACCOUNT;
	
	PROCEDURE INSERT_DISPLAY(SID IN SUPPLIER.SID%TYPE,SNAME IN SUPPLIER.SNAME%TYPE,ADDRESS IN SUPPLIER.ADDRESS%TYPE,IS_FOUND IN NUMBER)
	IS
	BEGIN
		IF IS_FOUND=1 THEN
			DBMS_OUTPUT.PUT_LINE('OUTPUT: ACCOUNT ALREADY EXISTS!');
		ELSE
			INSERT INTO SUPPLIER VALUES(SID,SNAME,ADDRESS);
			DBMS_OUTPUT.PUT_LINE('OUTPUT: ACCOUNT CREATED');
		END IF;
	END INSERT_DISPLAY;
	
END MYPACK;
/

CREATE OR REPLACE TRIGGER ON_INSERT
AFTER INSERT 
ON SUPPLIER
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('TRIGGER: NEW INFORMATION ADDED');
END;
/

ACCEPT X NUMBER PROMPT "ID = "
ACCEPT Y CHAR PROMPT "NAME = "
ACCEPT Z CHAR PROMPT "ADDRESS = "
DECLARE
	ID SUPPLIER.SID%TYPE;
	NAME SUPPLIER.SNAME%TYPE;
	ADDRESS SUPPLIER.ADDRESS%TYPE;
	IS_FOUND NUMBER;
	SID_NEG EXCEPTION;
	NOT_ALL_INPUT_MATCHED EXCEPTION;
BEGIN
	ID := &X;
	NAME := '&Y';
	ADDRESS := '&Z';
	
	IF ID<=0 THEN
		RAISE SID_NEG; 
	END IF;
	
	IS_FOUND := MYPACK.SEARCH_ACCOUNT(ID,NAME,ADDRESS);
	
	IF IS_FOUND = -1 THEN	
		RAISE NOT_ALL_INPUT_MATCHED;
	END IF;
	
	MYPACK.INSERT_DISPLAY(ID,NAME,ADDRESS,IS_FOUND);
	
EXCEPTION
	WHEN SID_NEG THEN
		DBMS_OUTPUT.PUT_LINE('EXCEPTION: ID MUST BE GREATER THEN 0');
	WHEN NOT_ALL_INPUT_MATCHED THEN
		DBMS_OUTPUT.PUT_LINE('EXCEPTION: ID MUST BE UNIQUE');
END;
/
SELECT * FROM SUPPLIER;