SET SERVEROUTPUT ON;
SET VERIFY OFF;

drop table TRAINING_SET;
create table TRAINING_SET(
	id integer, 
	outlook varchar2(30), 
	temp varchar2(30),
	humidity varchar2(30),
	wind varchar2(30),
	play varchar2(30),
	PRIMARY KEY (id)
);

CREATE OR REPLACE PACKAGE TRAIN_TEST_SPLIT AS
	PROCEDURE SPLIT(TRAINING_SIZE IN NUMBER);
END TRAIN_TEST_SPLIT;
/

CREATE OR REPLACE PACKAGE BODY TRAIN_TEST_SPLIT AS
	PROCEDURE SPLIT(TRAINING_SIZE IN NUMBER)
	AS
		NO_OF_ROWS NUMBER;
		LAST_INDEX INT;
	BEGIN
		SELECT COUNT(*) INTO NO_OF_ROWS FROM (SELECT * FROM tennis1 UNION SELECT * FROM tennis2@site1);
		LAST_INDEX:=NO_OF_ROWS*TRAINING_SIZE;
		FOR ATR IN (SELECT * FROM (SELECT * FROM tennis1 UNION SELECT * FROM tennis2@site1) WHERE ID<=LAST_INDEX) LOOP
			INSERT INTO TRAINING_SET VALUES(ATR.ID,ATR.OUTLOOK,ATR.TEMP,ATR.HUMIDITY,ATR.WIND,ATR.PLAY);
		END LOOP;
		COMMIT;
	END SPLIT;
END TRAIN_TEST_SPLIT;
/

