SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
	A MONEY.ID%TYPE;
	B MONEY.TAKA%TYPE;
BEGIN
	FOR R IN (SELECT * FROM MONEY) LOOP
		A:=R.ID;
		B:=R.TAKA;
		DBMS_OUTPUT.PUT_LINE(A||' '||B);
		IF MOD(B,2)=0 THEN
			DBMS_OUTPUT.PUT_LINE(B||' IS EVEN');
		ELSE
			DBMS_OUTPUT.PUT_LINE(B||' IS ODD');
		END IF;
	END LOOP;
END;
/