SET SERVEROUTPUT ON;
SET VERIFY ON;
-- VOID FUNCTION WITHOUT PARAMETER
CREATE OR REPLACE PROCEDURE f1
IS

BEGIN
	DBMS_OUTPUT.PUT_LINE('VOID FUNCTION WITHOUT PARAMETER');
END f1;
/

BEGIN
	f1;
END;
/
--ANOTHER WAY OF PROCEDURE CALL
EXEC f1; 

-- VOID FUNCTION WITH PARAMETER
CREATE OR REPLACE PROCEDURE printID(A IN MONEY.ID%TYPE)
IS

BEGIN
	DBMS_OUTPUT.PUT_LINE(A);
END printID;
/

BEGIN
	printID(2);
END;
/

--ANOTHER WAY OF PROCEDURE CALL
EXEC printID(4); 

-- RETURN FUNCTION WITH ACCEPTING VALUES IN PARAMETER
CREATE OR REPLACE PROCEDURE isEven(A IN MONEY.TAKA%TYPE,B OUT MONEY.ID%TYPE)
IS

BEGIN
	IF MOD(A,2)=0 THEN
		DBMS_OUTPUT.PUT_LINE(A || ' IS EVEN');
	ELSE
		DBMS_OUTPUT.PUT_LINE(A || ' IS ODD');
	END IF;
	SELECT MAX(ID) INTO B FROM MONEY;
END isEven;
/

DECLARE
	MAX_ID int;
BEGIN
	isEven(203,MAX_ID);
	DBMS_OUTPUT.PUT_LINE('MAX ID FROM MONEY IS = '||MAX_ID);
END;
/

ACCEPT X NUMBER PROMPT "ENTER MONEY = "
-- RETURN FUNCTION WITH ACCEPTING VALUES IN PARAMETER
CREATE OR REPLACE PROCEDURE F2(A IN OUT MONEY.TAKA%TYPE)
IS

BEGIN
	IF MOD(A,2)=0 THEN
		DBMS_OUTPUT.PUT_LINE(A || ' IS EVEN');
	ELSE
		DBMS_OUTPUT.PUT_LINE(A || ' IS ODD');
	END IF;
	A:=&X;
END F2;
/

DECLARE
	VAR_MONEY MONEY.TAKA%TYPE;
BEGIN
	VAR_MONEY:=220;
	F2(VAR_MONEY);
	DBMS_OUTPUT.PUT_LINE('MONEY = '||VAR_MONEY);
END;
/