SET SERVEROUTPUT ON;
SET VERIFY OFF;

--delete existing table
drop table train_test;

--Create train_test database
create table train_test(
	id integer, 
	testSize number,
	PRIMARY KEY (id)
);

CREATE OR REPLACE PROCEDURE test_size(NUM IN NUMBER)
AS
	NUM_EXP EXCEPTION;
BEGIN
	IF NUM>0 AND NUM<=1 THEN
		INSERT INTO train_test VALUES(1,NUM);
		COMMIT;
	ELSE
		RAISE NUM_EXP;
	END IF;

EXCEPTION
	WHEN NUM_EXP THEN
		DBMS_OUTPUT.PUT_LINE('EXCEPTION: YOUR GIVEN TEST SIZE IS INVALID (E.G. MUST BE IN RANGE 0-1)');
		DBMS_OUTPUT.PUT_LINE('DEFAULT TEST_SIZE=0.2 IS SELECTED');
		INSERT INTO train_test VALUES(1,0.2);
		COMMIT;
END test_size;
/

CREATE OR REPLACE TRIGGER ON_INSERT
AFTER INSERT
ON train_test
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('TRIGGER: NEW ROW INSERTED IN "train_test" TABLE');
END;
/

ACCEPT X NUMBER PROMPT "ENTER TEST_SIZE = "
DECLARE
	NUM NUMBER;
BEGIN
	NUM:=&X;
	test_size(NUM);
END;
/